image: registry.service.consul/ubuntu-build
env:
  - DOCKER_HOST=tcp://consul.service.consul:2375
  - REGISTRY=registry.service.consul
  - IMAGE_NAME=gogs
script:
  - env
  - cd $DRONE_BUILD_DIR
  - docker -H tcp://`ip r g 8.8.8.8 | awk '{ gsub(/\n$/,""); printf("%s", $3); }'`:2375 build --no-cache=true -t $REGISTRY/$IMAGE_NAME:$DRONE_BUILD_NUMBER .
  - docker -H tcp://`ip r g 8.8.8.8 | awk '{ gsub(/\n$/,""); printf("%s", $3); }'`:2375 push $REGISTRY/$IMAGE_NAME:$DRONE_BUILD_NUMBER
  - git remote add deploy ssh://git@devops-tools.pearson.com/mysdkr/gogs.git
  - git push deploy $DRONE_BRANCH

notify:
  hipchat:
    room: 866677
    token: b98efe858ce431baec6b5462ae01c2
    on_started: true
    on_success: true
    on_failure: true
